[env:default]
platform = intel_mcs51 @ 2.2.0
platform_packages =
   tool-stcgal @ 1.110.0
   tool-vnproch55x @ 1.0.220407
   toolchain-sdcc @ 1.40100.12072

board = STC8G1K08 # STC8G1K08A-8PIN

upload_port = /dev/ttyUSB0

board_upload.stcgal_protocol = stc8g
board_build.f_cpu = 11059200L

lib_deps =
    https://github.com/liux-pro/FwLib_STC8.git @ 1.0.0+sha.8af7df1

# Note: the -DUSB* is workaround for FWLib_STC8 support for STC8G series
build_flags =
    -D__CONF_MCU_MODEL=MCU_MODEL_STC8G1K08
    -D__CONF_FOSC=11059200L
    -DUSBADR=P0 -DUSBDAT=P0

extra_scripts = post:src/copyout_image.py
