M48
; DRILL file {KiCad 8.0.5-dirty} date 2024-12-22T20:18:58-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-22T20:18:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-dirty
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0728
%
G90
G05
T1
X5.6Y-3.45
X5.6Y-4.05
X6.0Y-3.45
X6.0Y-4.05
T2
X6.15Y-3.5
X6.15Y-3.6
X6.15Y-3.9
X6.15Y-4.0
T3
X5.6Y-3.622
X5.6Y-3.878
X5.7772Y-3.622
X5.7772Y-3.878
T4
X4.439Y-3.75
X5.2736Y-3.75
M30
